[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Matt Zhang", email = "set.stun@gmail.com"},
]
dependencies = [
    "magvit2-pytorch>=0.3.4",
    "torch>=2.1.2",
    "pytube>=15.0.0",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

